discription: None

save_name: STDN-CA

data_cfg:
  dataset_name: CASIA-B
  dataset_root: your_path
  num_workers: 8
  remove_no_gallery: false # Remove probe if no gallery for it
  test_dataset_name: CASIA-B


evaluator_cfg:
  enable_float16: true
  restore_ckpt_strict: true
  restore_hint: 100000
  eval_func: identification
  sampler:
    batch_shuffle: false
    batch_size: 1
    sample_type: all_ordered # all indicates whole sequence used to test, while ordered means input sequence by its natural order; Other options:   fixed_unordered
    frames_all_limit: 720 # limit the number of sampled frames to prevent out of memory
  metric: euc # cos
  transform:
    - type: BaseSilCuttingTransform
      img_w: 64


loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weight: 1.0
    scale: 1
    type: CrossEntropyLoss
    log_prefix: softmax
    log_accuracy: true


model_cfg:
  model: STDNet
  backbone_cfg:
    in_channels: 1
    depths: [1, 1, 1]
    dims: [64, 128, 256]
    downsample_stride: [1, 2, 1]
    type: STDN1TS
  
  SeparateFCs_1:
    in_channels: 256
    out_channels: 256
    parts_num: 64

  SeparateFCs_2:
    in_channels: 256
    out_channels: 74
    parts_num: 64

optimizer_cfg:
  lr: 3.e-4
  solver: Adam
  weight_decay: 0.


scheduler_cfg:
  gamma: 0.1
  milestones: # Learning Rate Reduction at each milestones
    - 90000
  scheduler: MultiStepLR


trainer_cfg:
  with_test: true
  enable_float16: true # half_percesion float for memory reduction and speedup
  fix_BN: false
  log_iter: 100
  restore_ckpt_strict: true
  restore_hint: 0
  save_iter: 10000
  sync_BN: true
  total_iter: 100000
  sampler:
    batch_shuffle: false
    batch_size:
      - 8 # TripletSampler, batch_size[0] indicates Number of Identity
      - 8 #  16               batch_size[1] indicates Samples sequqnce for each Identity
    frames_num_fixed: 30 # fixed frames number for training
    frames_skip_num: 0
    sample_type: fixed_ordered # fixed control input frames number, unordered for controlling order of input tensor; Other options: unfixed_ordered or all_ordered
    type: TripletSampler
  transform:
    - type: BaseSilCuttingTransform
      img_w: 64
